### ISSUE TITLE
Example run is not working

### ISSUE THREAD

**Issue by GulerEnes** [sentinel-hub/eo-flow#43]
I am trying to run the codes which are written in readme.md file on Google Colab. When I execute the command `$ python -m eoflow.execute configs/example.json ` this error occurring: 

> Traceback (most recent call last):
>   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/content/eo-flow/eoflow/execute.py", line 49, in <module>
>     execute(config_file=args.config_file)
>   File "/content/eo-flow/eoflow/execute.py", line 28, in execute
>     if not issubclass(model_cls, BaseModel):
>   File "/usr/lib/python3.7/abc.py", line 143, in __subclasscheck__
>     return _abc_subclasscheck(cls, subclass)
> TypeError: issubclass() arg 1 must be a class

I couldn't solve the error. Could you please help me?

**Comment by devisperessutti** [comment]
Hi @GulerEnes 

I'd need more details to help you out, e.g. `tensorflow` versions and `eo-learn` versions to start with.

I tried the example on a new 3.7 environment and it runs.
